export const enum FIELD_INDICES {
  AGENT_ID = 0,
  AGENT_EMAIL = 1,
  AGENT_NAME = 2,
  AGENT_PHONE = 3,
  OFFICE_ID = 4,
  OFFICE_NAME = 5,
  OFFICE_ADDRESS = 6,
  OFFICE_CITY = 7,
  OFFICE_STATE = 8,
  OFFICE_ZIP = 9,
  AGENT_ROLE = 10,
}
